language: java
jdk:
  - oraclejdk8
before_script:
  - mkdir /home/travis/webdriver
  - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/webdriver
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
script: mvn clean install
cache:
  directories:
  - $HOME/.m2
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer